name: CodeCov
run-name: ${{ github.actor }} - Checking Code Voverage
on: [push]
jobs:
  CodeCoverage:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Run triggered by a ${{ github.event_name }} event on ${{ github.repository }}@${{ github.ref }}"
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
      - run: echo "Status is ${{ job.status }}."