name: CodeCov
run-name: ${{ github.actor }} - Checking Code Voverage
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Run triggered by a ${{ github.event_name }} event on ${{ github.repository }}@${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "Checkout Successful"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - run: echo "Status is ${{ job.status }}."
